[package]
name = "wgpudev"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
bytemuck = "1.23.1"
futures = "0.3.31"
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4.50"
wgpu = "26.0.1"
